// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB7KwjPvobd2REnP5YUs7azqsetb6tvyck',
    appId: '1:280260361575:web:ba17e2e19b54cdc9d483c2',
    messagingSenderId: '280260361575',
    projectId: 'it-park-44a0a',
    authDomain: 'it-park-44a0a.firebaseapp.com',
    storageBucket: 'it-park-44a0a.appspot.com',
    measurementId: 'G-N8SYHF50L9',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBaDsca03YHEB3GjumZkJCZKcNMJS3xet0',
    appId: '1:280260361575:android:52e4b1bd9f30f0abd483c2',
    messagingSenderId: '280260361575',
    projectId: 'it-park-44a0a',
    storageBucket: 'it-park-44a0a.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCgMiUXYcNHqxamdV9baRUAC2PyIrFDyeU',
    appId: '1:280260361575:ios:e811277c160f3fced483c2',
    messagingSenderId: '280260361575',
    projectId: 'it-park-44a0a',
    storageBucket: 'it-park-44a0a.appspot.com',
    iosBundleId: 'com.example.interviewTaskTrissur',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCgMiUXYcNHqxamdV9baRUAC2PyIrFDyeU',
    appId: '1:280260361575:ios:e5aaa281f2332039d483c2',
    messagingSenderId: '280260361575',
    projectId: 'it-park-44a0a',
    storageBucket: 'it-park-44a0a.appspot.com',
    iosBundleId: 'com.example.interviewTaskTrissur.RunnerTests',
  );
}
